apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pods-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # You can adjust the role based on your requirements
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
# comment