{{- $baseName := printf "%s-%s-%s" .Release.Name (split "-" .Release.Namespace)._1 (split "-" .Release.Namespace)._2 }}
{{- $configMapName := printf "%s-%s" $baseName "spark-config-map" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
data:
  spark-defaults.conf: |
    spark.databricks.io.parquet.fastwriter.enabled=true
    spark.databricks.delta.preview.enabled=false
    spark.driver.maxResultSize=0
    spark.databricks.io.cache.enabled=false
    spark.databricks.io.parquet.nativeReader.enabled=true
    spark.sql.shuffle.partitions="{{ `{{ .shufflePartitions }}` }}"
    spark.sql.warehouse.dir=abfss://{{ `{{.containerName}}` }}@{{ `{{.storageAccountName}}` }}.dfs.core.windows.net/hive
    spark.hadoop.fs.azure.account.oauth2.client.secret="{{ `{{ .clientSecret }}` }}"
    fs.azure.account.oauth2.client.secret="{{ `{{ .clientSecret }}` }}"